version: '3'

services:
  webserver:
    image: 'nginx:1.17'
    ports:
      - 443:443
      - 80:80
    volumes:
      - './nginx:/etc/nginx/conf.d'
      - './nginx/ssl/:/etc/ssl/'
      - './frontend/build:/www/'
    depends_on:
      - api
  api:
    image: nchashch/animeshop-backend
    # build:
    #   context: ./backend
    #   args:
    #     - BINARY_PATH
    command: /opt/animeshop/backend
    depends_on:
      - database
  database:
    image: 'postgres:11.3'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
